###服务启动端口号
server:
  port: 8080
spring:
  application:
    name: atc_gene_web
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ghui?useUnicode=true&characterEncoding=UTF-8&useSSL=false

mybatis:
  mapper-locations: classpath:xml/*.xml
mybatis-plus:
  mapper-locations: classpath:xml/*.xml
###多线程配置
threadPool:
  ###核心线程数
  corePoolSize: 10
  ###最大线程数
  maxPoolSize: 20
  ##  队列容量
  queueCapacity: 16


